### ISSUE TITLE
make sure to comment main parts of code 

### ISSUE THREAD

**Issue by ad3429** [oliviagrech/prj-rev-bwfs-tea-cozy#2]
https://github.com/oliviagrech/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/index.html#L1-L90

I noticed you have 1 comment in your HTML, but you should make sure to comment the main parts of your code for organizational purposes. This makes your code much easier to follow and read. Here is a quick reminder on commenting in HTML:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/31856250-4df3c916-b68a-11e7-876f-2583a5a91240.png">

**Comment by oliviagrech** [comment]
Thank you for pointing this out. I added some comments to my HTML code and submitted an updated version containing comments.
