### ISSUE TITLE
CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [oliviagrech/prj-rev-bwfs-tea-cozy#3]
https://github.com/oliviagrech/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/css/style.css#L1-L118

Your CSS is short, clean and succinct -- make sure to keep it up. You also did a good job of commenting your main stylings, which is something that many learners forget to do. Good job!

**Comment by oliviagrech** [comment]
Thank you!
